-- MySQL Script generated by MySQL Workbench
-- Mon Mar 12 14:06:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema market
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `market` DEFAULT CHARACTER SET utf8 ;
USE `market` ;

-- -----------------------------------------------------
-- Table `market`.`rain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`rain` (
  `date` DATETIME NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`products` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `amount` VARCHAR(45) NOT NULL,
  `metric` VARCHAR(45) NOT NULL,
  `cost` DECIMAL(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`poulty_houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`poulty_houses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`poultry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`poultry` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `breed` VARCHAR(45) NOT NULL,
  `birth` DATETIME NULL,
  `house` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `house_idx` (`house` ASC),
  CONSTRAINT `house`
    FOREIGN KEY (`house`)
    REFERENCES `market`.`poulty_houses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
